import { ReactNode } from 'react';
import Head from 'next/head';
import { Navbar } from '../Navbar';
import styles from '../../styles/Layout.module.css';

interface propsWithChildren {
    children: ReactNode
}

export const MainLayout = ({ children }: propsWithChildren): JSX.Element => {
    return (
        <>
            <Head>
                <title>Home-App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name='keywords' content='Prisciliano, course, next' />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Navbar />

            <main className={styles.main}>
                { children }
            </main>
        </>
    )
}
